ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MH

      COMMON/MASSES/ MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MH


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX R2_DDA, R2_UUA, R2_UUZ_V2, R2_UUZ_V5, R2_SXCW,
     $  GC_5, R2_QQQ, GC_1, GC_2, GC_7, GC_22, GC_23, GC_25, GC_26,
     $  GC_47

      COMMON/COUPLINGS/ R2_DDA, R2_UUA, R2_UUZ_V2, R2_UUZ_V5, R2_SXCW,
     $  GC_5, R2_QQQ, GC_1, GC_2, GC_7, GC_22, GC_23, GC_25, GC_26,
     $  GC_47

