ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'R2_DDA = ', R2_DDA
      WRITE(*,2) 'R2_UUA = ', R2_UUA
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'R2_UUZ_V5 = ', R2_UUZ_V5
      WRITE(*,2) 'R2_sxcW = ', R2_SXCW
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'R2_QQq = ', R2_QQQ
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_25 = ', GC_25
      WRITE(*,2) 'GC_26 = ', GC_26
      WRITE(*,2) 'GC_47 = ', GC_47
