C     Diagram 1, Amplitude 1
      DATA MAPCONFIG(   1)/   1/
      DATA (IFOREST(I, -1,   1),I=1,2)/  4,  3/
      DATA SPROP(  -1,   1)/     -24/
      DATA (IFOREST(I, -2,   1),I=1,2)/  5, -1/
      DATA SPROP(  -2,   1)/     -24/
C     Diagram 2, Amplitude 2
      DATA MAPCONFIG(   2)/   2/
      DATA (IFOREST(I, -1,   2),I=1,2)/  5,  3/
      DATA SPROP(  -1,   2)/     -24/
      DATA (IFOREST(I, -2,   2),I=1,2)/  4, -1/
      DATA SPROP(  -2,   2)/     -24/
C     Diagram 4, Amplitude 4
      DATA MAPCONFIG(   3)/   4/
      DATA (IFOREST(I, -1,   3),I=1,2)/  1,  3/
      DATA TPRID(  -1,   3)/       2/
      DATA (IFOREST(I, -2,   3),I=1,2)/ -1,  5/
      DATA TPRID(  -2,   3)/       2/
      DATA (IFOREST(I, -3,   3),I=1,2)/ -2,  4/
C     Diagram 5, Amplitude 5
      DATA MAPCONFIG(   4)/   5/
      DATA (IFOREST(I, -1,   4),I=1,2)/  1,  3/
      DATA TPRID(  -1,   4)/       2/
      DATA (IFOREST(I, -2,   4),I=1,2)/ -1,  4/
      DATA TPRID(  -2,   4)/       2/
      DATA (IFOREST(I, -3,   4),I=1,2)/ -2,  5/
C     Diagram 6, Amplitude 6
      DATA MAPCONFIG(   5)/   6/
      DATA (IFOREST(I, -1,   5),I=1,2)/  1,  4/
      DATA TPRID(  -1,   5)/       1/
      DATA (IFOREST(I, -2,   5),I=1,2)/ -1,  5/
      DATA TPRID(  -2,   5)/       1/
      DATA (IFOREST(I, -3,   5),I=1,2)/ -2,  3/
C     Diagram 7, Amplitude 7
      DATA MAPCONFIG(   6)/   7/
      DATA (IFOREST(I, -1,   6),I=1,2)/  1,  4/
      DATA TPRID(  -1,   6)/       1/
      DATA (IFOREST(I, -2,   6),I=1,2)/ -1,  3/
      DATA TPRID(  -2,   6)/       2/
      DATA (IFOREST(I, -3,   6),I=1,2)/ -2,  5/
C     Diagram 8, Amplitude 8
      DATA MAPCONFIG(   7)/   8/
      DATA (IFOREST(I, -1,   7),I=1,2)/  5,  3/
      DATA SPROP(  -1,   7)/     -24/
      DATA (IFOREST(I, -2,   7),I=1,2)/  1,  4/
      DATA TPRID(  -2,   7)/       1/
      DATA (IFOREST(I, -3,   7),I=1,2)/ -2, -1/
C     Diagram 9, Amplitude 9
      DATA MAPCONFIG(   8)/   9/
      DATA (IFOREST(I, -1,   8),I=1,2)/  1,  5/
      DATA TPRID(  -1,   8)/       1/
      DATA (IFOREST(I, -2,   8),I=1,2)/ -1,  4/
      DATA TPRID(  -2,   8)/       1/
      DATA (IFOREST(I, -3,   8),I=1,2)/ -2,  3/
C     Diagram 10, Amplitude 10
      DATA MAPCONFIG(   9)/  10/
      DATA (IFOREST(I, -1,   9),I=1,2)/  1,  5/
      DATA TPRID(  -1,   9)/       1/
      DATA (IFOREST(I, -2,   9),I=1,2)/ -1,  3/
      DATA TPRID(  -2,   9)/       2/
      DATA (IFOREST(I, -3,   9),I=1,2)/ -2,  4/
C     Diagram 11, Amplitude 11
      DATA MAPCONFIG(  10)/  11/
      DATA (IFOREST(I, -1,  10),I=1,2)/  4,  3/
      DATA SPROP(  -1,  10)/     -24/
      DATA (IFOREST(I, -2,  10),I=1,2)/  1,  5/
      DATA TPRID(  -2,  10)/       1/
      DATA (IFOREST(I, -3,  10),I=1,2)/ -2, -1/
C     Diagram 12, Amplitude 12
      DATA MAPCONFIG(  11)/  12/
      DATA (IFOREST(I, -1,  11),I=1,2)/  5,  3/
      DATA SPROP(  -1,  11)/     -24/
      DATA (IFOREST(I, -2,  11),I=1,2)/  1, -1/
      DATA TPRID(  -2,  11)/       2/
      DATA (IFOREST(I, -3,  11),I=1,2)/ -2,  4/
C     Diagram 13, Amplitude 13
      DATA MAPCONFIG(  12)/  13/
      DATA (IFOREST(I, -1,  12),I=1,2)/  4,  3/
      DATA SPROP(  -1,  12)/     -24/
      DATA (IFOREST(I, -2,  12),I=1,2)/  1, -1/
      DATA TPRID(  -2,  12)/       2/
      DATA (IFOREST(I, -3,  12),I=1,2)/ -2,  5/
C     Number of configs
      DATA MAPCONFIG(0)/  12/
